### ISSUE TITLE
specdb_plot now crashes

### ISSUE THREAD

**Issue by jhennawi** [specdb/igmspec#98]
qso-laptop:joe% specdb_plot J003525.28+004002.8 igmspec --group SDSS_DR7
Loading igmspec from /Users/joe/IGMSPEC_DB/IGMspec_DB_v02.hdf5
Database is igmspec
Created on 2016-Dec-13
Version: v02
Your search yielded 1 match[es] within radius=5 arcsec
Staged 1 spectra totalling 8e-05 Gb
Loaded spectra
/Users/joe/python/linetools/linetools/spectra/xspectrum1d.py:249: UserWarning: No unit given to wavelength, assuming Angstroms.
  warnings.warn("No unit given to wavelength, assuming Angstroms.")
Source located in group: SDSS_DR7
Traceback (most recent call last):
  File "/Users/joe/anaconda3/bin//specdb_plot", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/joe/python/specdb/bin/specdb_plot", line 16, in <module>
    plot_specdb.main(args)
  File "/Users/joe/python/specdb/specdb/scripts/plot_specdb.py", line 62, in main
    print(meta[['INDEX','GROUP','RA_GROUP','DEC_GROUP',Specdb.idkey,'INSTR','DISPERSER','GROUP_ID']])
  File "/Users/joe/anaconda3/lib/python3.6/site-packages/astropy/table/table.py", line 1234, in __getitem__
    .format(', '.join(bad_names)))
ValueError: Slice name(s) DISPERSER not valid column name(s)

**Comment by profxj** [comment]
I am not getting any error with v2.1 of igmspec

Try grabbing that with specdb, i.e.

specdb_get_igmspec
